services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - UMASK_SET=022
          - WEBUI_PORT=8082
        volumes:
          - /mnt/dockerdrive/mediaserver/qbittorrentdata/config/:/config
          - /mnt/dockerdrive/mediaserver/qbittorentdata/downloads:/downloads
        ports:
          - 6881:6881
          - 6881:6881/udp
          - 8082:8082
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /mnt/dockerdrive/mediaserver//radarr/:/config            
            - /mnt/dockerdrive/movies/:/movies
            - /mnt/d/movies/:/movies2
            - /mnt/dockerdrive/mediaserver/qbittorentdata/downloads:/downloads         
        ports:
            - 7878:7878
        restart: unless-stopped
        depends_on: 
            - qbittorrent    
    
    embyserver:
        image: lscr.io/linuxserver/emby:latest
        container_name: embyserver
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /mnt/dockerdrive/mediaserver/embyserver/config:/config
            - /mnt/dockerdrive/mediaserver/embyserver/transcode:/transcode
            - /mnt/dockerdrive/movies:/media/movies
            - /mnt/d/movies:/media/movies2
            - /mnt/dockerdrive/music:/media/music
            - /mnt/dockerdrive/tv:/media/tv
        ports:
            - 8096:8096
        restart: unless-stopped
        depends_on: 
            - qbittorrent                 
    
    prowlarr:
        image: lscr.io/linuxserver/prowlarr
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /mnt/dockerdrive/mediaserver/prowlarr/config:/config
            - /mnt/dockerdrive/mediaserver/prowlarr/downloads:/downloads
            - /mnt/dockerdrive/mediaserver/prowlarr/tv:/tv
        ports:
            - 9696:9696
        restart: unless-stopped
        depends_on: 
            - qbittorrent         
    
    sonarr:
        image: lscr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /mnt/dockerdrive/mediaserver/sonarr/config:/config
            - /mnt/dockerdrive/mediaserver/downloads:/downloads
            - /mnt/dockerdrive/tv:/tv
            - /mnt/dockerdrive/mediaserver/qbittorentdata/downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
        depends_on: 
            - qbittorrent

    tunnel:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        environment:
            - TUNNEL_URL=http://embyserver:8096
            - TUNNEL_TOKEN=eyJhIjoiODE4YTkyNDk1ZDZmNDdlMmY1M2U3ZGJjMDRlYjg5YjgiLCJ0IjoiMjZiZDc5MGEtZjAzZC00NzEyLThlODUtMDA1OGUyZTdkYTEzIiwicyI6Ik4yTmhZMlEyWmpJdE5qUXdOUzAwTUdFeUxUbGtNelV0WXpVMk5EWTBaV1V4Tm1FeSJ9
        command: tunnel run
        depends_on:
        - embyserver

    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC`
        volumes:
        - /mnt/dockerdrive/mediaserver/jackett/data:/config
        - /mnt/dockerdrive/mediaserver/downloads:/downloads
        ports:
        - 9117:9117
        restart: unless-stopped
