version: '2'
services:
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - UMASK_SET=022
          - WEBUI_PORT=8080
        volumes:
          - /path/to/appdata/config:/config
          - /path/to/downloads:/downloads
        ports:
          - 6881:6881
          - 6881:6881/udp
          - 8080:8080
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - UMASK_SET=022 #optional
        volumes:
            - path to data:/config
            - path/to/tvseries:/tv
            - path/to/downloadclient-downloads:/downloads
        ports:
            - 8989:8989
        depends_on: 
            - qbittorrent
        restart: unless-stopped