services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - UMASK_SET=022
          - WEBUI_PORT=8082
        volumes:
          - D:/mediaserver/qbittorrentdata/config/:/config
          - D:/mediaserver/qbittorentdata/downloads:/downloads
        ports:
          - 6881:6881
          - 6881:6881/udp
          - 8082:8082
        restart: unless-stopped

    # radarr:
    #     image: lscr.io/linuxserver/radarr
    #     container_name: radarr
    #     environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=Europe/London
    #     volumes:
    #         - D:/mediaserver//radarr/:/config            
    #         - D:/movies/:/movies
    #         - D:/mediaserver/qbittorentdata/downloads:/downloads         
    #     ports:
    #         - 7878:7878
    #     depends_on: 
    #         - qbittorrent    
    
    embyserver:
        image: lscr.io/linuxserver/emby:latest
        container_name: embyserver
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - D:/mediaserver/embyserver/config:/config
            - D:/mediaserver/embyserver/transcode:/transcode
            - D:/movies:/media/movies
            - D:/music:/media/music
            - D:/tv:/media/tv
        ports:
            - 8096:8096
        restart: unless-stopped
        depends_on: 
            - qbittorrent                 
    
    prowlarr:
        image: lscr.io/linuxserver/prowlarr
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - D:/mediaserver/prowlarr/config:/config
            - D:/mediaserver/prowlarr/downloads:/downloads
            - D:/mediaserver/prowlarr/tv:/tv
        ports:
            - 9696:9696
        restart: unless-stopped
        depends_on: 
            - qbittorrent         
    
    sonarr:
        image: lscr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - D:/mediaserver/sonarr/config:/config
            - D:/mediaserver/downloads:/downloads
            - D:/tv:/tv
            - D:/mediaserver/qbittorentdata/downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
        depends_on: 
            - qbittorrent

    # lidarr:
    #     image: lscr.io/linuxserver/lidarr:latest
    #     container_name: lidarr
    #     environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Etc/UTC
    #     volumes:
    #     - D:/mediaserver/liadrr/config:/config
    #     - D:/mediaserver/music:/music #optional
    #     - D:/mediaserver/Downloads:/downloads #optional
    #     - D:/mediaserver/qbittorentdata/downloads:/downloads
    #     ports:
    #     - 8686:8686
    #     restart: unless-stopped
    #     depends_on: 
    #         - qbittorrent



