version: '3'
services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - UMASK_SET=022
          - WEBUI_PORT=8082 
        volumes:
          - D:/mediaserver/qbittorrentdata/config/:/config
          - D:/mediaserver/qbittorentdata/downloads:/downloads
        ports:
          - 6881:6881
          - 6881:6881/udp
          - 8082:8082
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London            
        volumes:
            - D:/mediaserver//radarr/:/config            
            - D:/movies/:/movies
            - E:/movies/:/movies2
        ports:
            - 7879:7878
        depends_on: 
            - qbittorrent    
    
    embyserver:
        image: lscr.io/linuxserver/emby:latest
        container_name: embyserver
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - D:/mediaserver/embyserver/config:/config
            - D:/mediaserver/embyserver/transcode:/transcode
            - E:/movies:/media/movies
            - D:/music:/media/music
        ports:
            - 8097:8096
        restart: unless-stopped
        depends_on: 
            - qbittorrent         
    
    prowlarr:
        image: lscr.io/linuxserver/prowlarr
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - D:/mediaserver/prowlarr/config:/config
            - D:/mediaserver/prowlarr/downloads:/downloads
            - D:/mediaserver/prowlarr/tv:/tv
        ports:
            - 9697:9696
        restart: unless-stopped
        depends_on: 
            - qbittorrent         
    
    sonarr:
        image: lscr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - D:/mediaserver/sonarr/config:/config
            - D:/mediaserver/sonarr/downloads:/downloads
            - D:/mediaserver/sonarr/tv:/tv
        ports:
            - 8990:8989
        restart: unless-stopped
        depends_on: 
            - qbittorrent

    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        volumes:
        - D:/mediaserver/liadrr/config:/config
        - D:/music:/music #optional
        - E:/Downloads:/downloads #optional
        ports:
        - 8686:8686
        restart: unless-stopped
        depends_on: 
            - qbittorrent



