version: '3'
services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - UMASK_SET=022
          - WEBUI_PORT=8082 
        volumes:
          - /share/Software/qbittorrentdata/config/:/config
          - /share/Software/qbittorentdata/downloads:/downloads
        ports:
          - 6881:6881
          - 6881:6881/udp
          - 8082:8082
        networks:
          - frontend
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London            
        volumes:
            - /software/radarr/:/config            
            - /movies/:/movies
            - /movies2/:/movies2
        ports:
            - 7878:7878
        networks:
            - frontend
        depends_on: 
            - qbittorrent
    
    jackett:
      image: lscr.io/linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=<run options here> #optional
      volumes:
        - /share/software/jackett/data:/config #
        - /share//software/jackett/blackhole:/downloads
      ports:
        - 9117:9117
      networks:
        - frontend
      restart: unless-stopped
