version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Software/radarr/config:/config
      - /share/Movies:/movies #optional
      - /share/CACHEDEV1_DATA/.qpkg/qBittorrent/Downloads:/radarrdownloads #optional
    ports:
      - 7880:7878
    restart: unless-stopped